# Generated by Django 4.2.3 on 2023-12-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_professores',
            },
        ),
    ]
